apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mathapp
  template:
    metadata:
      labels:
        app: mathapp
    spec:
      containers:
        - name: mathapp
          image: mathapp:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mathapp-service
spec:
  selector:
    app: mathapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer